### PR TITLE
Rwj11/556a investigate what unit tests can be added

### PR DESCRIPTION
**Pull request by rwj11**
The packing & unpacking operations now have exploratory unit tests, and the code has been refactored to be (for the most part) independent of the `MAX_NUMBERS` parameter.
It would probably be useful to refactor further to place the size of the data at the head of the block to check integrity of the unpack operation, and to pack bitwise rather than converting to `double` and back -- these kind of changes should hopefully be enabled by having tests in place, and by the localization of policy in the revised code.

### CODE REVIEW

**Comment by rwj11** [comment]
Note that the templates now used in pack.cc are carefully insulated from external users, but would be useful to add a comment at the head of `pack.cc` giving hints on how to extend this functionality.  `MPI_Pack` could potentially be used to implement capability.

**Comment by theITEAM** [comment]
Hi Robin,

Thanks. I'm not quite sure I understand your comment, sorry abou that... it is just my lack of knowledge.

**Comment by rwj11** [comment]
The comment is just summarizing some issues which were raised in a side-discussion, and are specific to the functionality of the (low-level infrastructure) code modified on this branch.

**Comment by theITEAM** [comment]
Thanks.

**Pull request merged**
