### PR TITLE
Ianhinder/605 write q to outputdir

### PR DESCRIPTION
**Pull request by ianhinder**
See https://github.com/ScottishCovidResponse/SCRCIssueTracking/issues/605.

Write the Q matrices to the output directory.

### CODE REVIEW

**Comment by rwj11** [comment]
The CI failure probably just requires merging up to date with dev.

**Comment by rwj11** [comment]
Looks fine in general.  Can `#include <sys/stat.h>` now be removed from `output.cc` (and `obsmodel.hh`)?

**Comment by ianhinder** [comment]
Probably. I'll take a look. Just waiting for an OK from @chrispooley about changing the output location.

**Comment by ianhinder** [comment]
Implemented

**Pull request closed without merging**
