### PR TITLE
Rwj11/617 remove memory leak in mbp

### PR DESCRIPTION
**Pull request by rwj11**
I changed this from a file-static vector of pointers to a vector member of a wrapper class.  This means it doesn't leak and is at least a bit closer to re-entrant.
I also did some associated work to make the doxygen call tree more representative -- I have the current version installed, but it still seems to struggle with some pretty well-established C++ syntax.

### CODE REVIEW

**Comment by ianhinder** [comment]
Would it make sense to rename MBP_impl as MBP, have the caller construct an MBP object, and then run it with a .run(...) method, which would replace the current MBP function? That might be a bit more expected, rather than having a free function which instantiates an object.

**Comment by rwj11** [comment]
Probably in the long term.  I did things in the way I did so that this work within the existing public interface of MBP.

**Comment by ianhinder** [comment]
OK - since it's only called in one place, I wouldn't worry about it.  Could you make that change, so we can merge it before we start getting conflicts?

**Comment by rwj11** [comment]
> since it's only called in one place, I wouldn't worry about it.

In design terms, I think this is exactly the reason _not_ to make this change.  The resulting object could be `.run()` 0, 2, 3, 4... times (does that even make sense as things stand?), would need to hold references to its arguments (so would be a magnet for undefined behaviour), and for someone working in the exterior domain it wouldn't be obvious why it needed to be an object in the first place.  So I'd argue for YAGNI, at least until it seems clearer which aggregates make sense, rather than just being expedient.

I converted the object to a workspace struct, and passed that around as an argument to free functions in the anonymous namespace (i.e. C++'s preferred equivalent of file static linkage), which was probably a better thing to do in the first place.

**Comment by ianhinder** [comment]
I tried to fix the merge conflicts, but ended up with failed tests. My attempt is in ianhinder/617_remove_memory_leak_in_MBP_brokenmerge.

**Pull request merged**
